### ISSUE TITLE
self.gate is never used?

### ISSUE THREAD

**Issue by inspirit** [lucidrains/token-shift-gpt#1]
it seems like self.gate is never actually used, or am I missing something?

https://github.com/lucidrains/token-shift-gpt/blob/1449b263f1fb222279d00f9128c29f25dbef976b/token_shift_gpt/token_shift_gpt.py#L79

**Comment by lucidrains** [comment]
@inspirit oops, i had a causal squeeze excitation in there originally, fixed!
